"""Renders report.md for the learned-semantic-graph analysis (Stage 0b).

No hard-coded results; every number is interpolated from the metrics dict.
Describes the evidence and does not interpret. Python 3.9 compatible.
"""
from __future__ import annotations

from typing import Dict

import numpy as np

from ..evaluation import influence_graph as ig


def _f(x, nd=3):
    if x is None:
        return "n/a"
    if isinstance(x, float):
        return "n/a" if np.isnan(x) else "{:.{}f}".format(x, nd)
    return str(x)


def render(res: Dict, geo: ig.Geometry) -> str:
    g, s = res["geometry"], res["settings"]
    per = res["per_checkpoint"]
    names = list(per.keys())
    primary = "metr_la_best.pt" if "metr_la_best.pt" in per else names[0]
    p = per[primary]
    par = p["parameterisation"]
    L = []
    A = L.append

    A("# The learned semantic graph, read out of the checkpoint")
    A("")
    A("**Status: EXPLORATORY.** No GNN solves, no explainer, no LLM. `A_sem` is a")
    A("stored parameter, so everything here is a static read plus arithmetic and is")
    A("exactly reproducible from the checkpoint files alone.")
    A("")
    A("This is the companion to the explainer analysis. Where that asks *what does the")
    A("explainer say the model leans on*, this asks *what does the model's own learned")
    A("graph look like* — a question that needs no solves at all.")
    A("")

    # ---------------------------------------------------------------- item 1
    A("## 1. What the object is")
    A("")
    A("`XTrafficSTGNN` blends two graphs into its first support (`stgnn.py:261-268`):")
    A("")
    A("```")
    A("A_final = sigmoid(alpha) * A_phys + (1 - sigmoid(alpha)) * A_sem")
    A("A_sem   = softmax(relu(E @ E.T), dim=1),   E = sem_embed [N, embed_dim]")
    A("```")
    A("")
    A("| Property | Value |")
    A("|---|---|")
    A("| Parameterisation | `{}` |".format(par["parameterisation"]))
    A("| `sem_embed` shape | {} (embed_dim {}) |".format(
        par["embed_shape"], par["embed_dim"]))
    A("| Rank of pre-softmax `E @ E.T` | {} (bound {}) |".format(
        par["measured_rank_of_pre_softmax"], par["rank_bound_of_pre_softmax"]))
    A("| Initialisation | {} |".format(par["initialisation"]))
    A("| **Seeded from the kernel adjacency?** | **{}** |".format(
        "yes" if par["seeded_from_kernel_adjacency"] else "no"))
    A("| Pre-softmax symmetric | {} |".format(par["pre_softmax_symmetric"]))
    A("| Post-softmax symmetric | {} |".format(par["post_softmax_symmetric"]))
    A("| **Directed** | **{}** |".format(par["directed"]))
    A("| Normalisation | {} |".format(par["normalisation"]))
    A("| Row sums | {} to {} |".format(par["row_sums_min"], par["row_sums_max"]))
    A("")
    A("**It is not initialised from the adjacency.** `sem_embed` starts at")
    A("`torch.randn(N, embed_dim) * 0.01` (`stgnn.py:239`), so `A_sem` is learned from")
    A("random init rather than as a correction to the given graph. The difference")
    A("between the two is therefore *not* the object of study: `A_sem` is its own")
    A("graph, and comparing it to the adjacency is the same kind of comparison the")
    A("explainer analysis makes.")
    A("")
    A("**The directionality is an artefact of normalisation, not of learning.**")
    A("{}".format(par["asymmetry_source"]))
    A("")
    A("**The similarity is low-rank.** `E @ E.T` has measured rank {} with embed_dim".format(
        par["measured_rank_of_pre_softmax"]))
    A("{}, so all {} pairwise scores are generated by a {}-dimensional embedding.".format(
        par["embed_dim"], geo.n * geo.n, par["embed_dim"]))
    A("")
    A("### Effective sparsity")
    A("")
    es = par["effective_sparsity"]
    ss = par["structural_sparsity"]
    A("Structural sparsity is **zero by construction** — softmax leaves {} of {}".format(
        ss["strictly_positive_entries"], ss["total_entries"]))
    A("entries strictly positive ({:.0%}). The meaningful measure is concentration:".format(
        ss["share_positive"]))
    A("")
    A("| Measure | Value | Uniform reference |")
    A("|---|---|---|")
    A("| Row perplexity `exp(entropy)` — effective number of targets a source spreads over | mean **{}**, median {}, range {}-{} | {} |".format(
        es["perplexity_mean"], es["perplexity_median"], es["perplexity_min"],
        es["perplexity_max"], es["perplexity_uniform_reference"]))
    A("| Mass in a row's top {} | mean **{}**, median {} | {} |".format(
        s["top_k"], es["top8_row_mass_mean"], es["top8_row_mass_median"],
        es["uniform_top8_mass_reference"]))
    A("| Off-diagonal pairs sitting on the ReLU floor | **{:.1%}** | — |".format(
        es["relu_floor_share_of_offdiag_pairs"]))
    A("")
    A("The ReLU floor is a structural quirk worth stating: `relu` maps every negative")
    A("similarity to exactly 0, and those pairs then enter the softmax at the identical")
    A("value `exp(0)`. {:.1%} of off-diagonal pairs are in that state, so **the graph".format(
        es["relu_floor_share_of_offdiag_pairs"]))
    A("does not distinguish between them at all** — they share one flat weight rather")
    A("than a range of small ones.")
    A("")

    # ---------------------------------------------------------------- item 2
    A("## 2. The learned graph against the given adjacency")
    A("")
    A("`A_sem` is indexed `[source, target]` under the `einsum('bcnt,nm->bcmt')`")
    A("convention, so `W_learned` is its transpose. Same two threshold rules, same")
    A("baselines, same hop stratification as the explainer analysis.")
    A("")
    A("### Primary checkpoint: `{}`".format(primary))
    A("")
    A("| Rule | \\|E\\| | Precision | Recall | Jaccard | Off-adjacency |")
    A("|---|---|---|---|---|---|")
    for lab, key in (("top-k (k={})".format(s["top_k"]), "top_k"),
                     ("cumulative mass {:.0%}".format(s["mass_frac"]), "cumulative_mass")):
        m = p["edges"][key]
        A("| {} | {} | {} | {} | {} | {} |".format(
            lab, m["n_effective"], _f(m["precision"]), _f(m["recall"]),
            _f(m["jaccard"]), m["n_off_adjacency"]))
    A("")
    A("**Baselines** (all {} targets, same k)".format(g["n_nodes"]))
    A("")
    A("| Method | \\|E\\| | Precision | Recall | Jaccard |")
    A("|---|---|---|---|---|")
    m = p["edges"]["top_k"]
    A("| **learned semantic top-k** | {} | **{}** | {} | {} |".format(
        m["n_effective"], _f(m["precision"]), _f(m["recall"]), _f(m["jaccard"])))
    for bn, lab in (("uniform_random", "(a) uniform random"),
                    ("degree_matched_random", "(b) degree-matched random"),
                    ("nearest_by_road_distance", "(c) nearest by road distance")):
        b = p["baselines"][bn]
        A("| {} | {} | {} | {} | {} |".format(
            lab, b["n_effective"], _f(b["precision"]), _f(b["recall"]), _f(b["jaccard"])))
    A("")
    uni = p["baselines"]["uniform_random"]["precision"]
    if uni:
        A("Learned-vs-uniform precision ratio: **{}x**.".format(_f(m["precision"] / uni, 2)))
    A("Overlap with the nearest-by-road set (Jaccard): {}.".format(
        _f(p["overlap_with_nearest_road"])))
    A("")
    A("**Mass on adjacency edges** (a normalisation-free view — no thresholding):")
    A("")
    A("| Support | Mass on adjacency edges | Chance | Lift |")
    A("|---|---|---|---|")
    for key, lab in (("road_alignment_semantic", "semantic `A_sem` (the (1-alpha) term)"),
                     ("road_alignment_adaptive", "adaptive (second support, secondary)")):
        r = p[key]
        A("| {} | {} | {} | **{}x** |".format(
            lab, _f(r["mass_on_adjacency_edges"], 4),
            _f(r["adjacency_share_of_pairs"], 5), _f(r["lift_over_chance"], 2)))
    A("")
    A("### Hop-distance stratification (`{}`)".format(primary))
    A("")
    A("| Hop bucket | Edges | Share |")
    A("|---|---|---|")
    for h in p["hop_strata"]:
        A("| {} | {} | {} |".format(h["bucket"], h["n_effective_edges"],
                                    _f(h["share_of_effective"])))
    A("")
    bk = p["beyond_k"]
    A("Beyond {} hops or unreachable: **{} edges** ({} of the set), {} unreachable.".format(
        bk["k_hops"], bk["n_edges"], _f(bk["share_of_effective"]), bk["n_unreachable"]))
    A("As in the explainer analysis, both supports are dense so this is not by itself")
    A("anomalous — it describes where the learned mass sits relative to the road graph.")
    A("")
    A("Full edge listings: `learned_edges.csv`, `learned_off_adjacency_edges.csv`")
    A("(road distance and haversine in separate columns; nothing derived from")
    A("haversine), `learned_hop_strata.csv`, `learned_baselines.csv`.")
    A("")
    A("### How flat is it?")
    A("")
    sf = p["sources_for_mass_frac"]
    A("Sources needed to cover {:.0%} of a target's off-self mass: mean **{}**,".format(
        sf["mass_frac"], sf["mean"]))
    A("median {}, range {}-{}, out of {} available.".format(
        sf["median"], sf["min"], sf["max"], sf["of_available"]))
    A("")

    # ---------------------------------------------------------------- item 3
    A("## 3. Stability across checkpoints")
    A("")
    A("`A_sem` does not vary by window, so split-half does not apply. The equivalent")
    A("question is whether different training states agree.")
    A("")
    A("Checkpoints on disk with N=207: **{}**.".format(", ".join("`{}`".format(n) for n in names)))
    A("")
    A("| Checkpoint | Epoch | val MAE | run | sigmoid(alpha) | top-k precision |")
    A("|---|---|---|---|---|---|")
    for n in names:
        c = per[n]["checkpoint"]
        A("| `{}` | {} | {} | {} | {} | {} |".format(
            n, c["epoch"], _f(c["val_mae"], 5), c["run_name"] or "—",
            _f(per[n]["alpha"]["sigmoid_alpha"], 4),
            _f(per[n]["edges"]["top_k"]["precision"])))
    A("")
    st = res["cross_checkpoint_stability"]
    A("| Pair | top-k Jaccard | mean per-target Spearman |")
    A("|---|---|---|")
    for r in st["pairwise_topk_jaccard"]:
        A("| `{}` vs `{}` | **{}** | {} |".format(
            r["a"], r["b"], _f(r["topk_jaccard"], 4), _f(r["spearman_mean"], 4)))
    A("| *reference: two independent uniform random draws* | {} | — |".format(
        _f(st["two_random_draws_reference"], 4)))
    A("")
    A("{}".format(st["note"]))
    A("")
    A("Excluded checkpoints — {}: {}.".format(
        res["checkpoints_excluded"]["reason"],
        ", ".join("`{}`".format(f) for f in res["checkpoints_excluded"]["files"])))
    A("")

    # ---------------------------------------------------------------- item 4
    A("## 4. The alpha trajectory")
    A("")
    A("`sigmoid(alpha)` is the weight on the **given** adjacency; `1 - sigmoid(alpha)`")
    A("is the weight on the **learned** semantic graph. It initialises at")
    A("`sigmoid(0) = 0.5` (`stgnn.py:240`).")
    A("")
    A("| Checkpoint | Epoch | run | weight on given adjacency | weight on learned graph |")
    A("|---|---|---|---|---|")
    for a in res["alpha_trajectory"]:
        al = a["sigmoid_alpha"]
        A("| `{}` | {} | {} | {} | {} |".format(
            a["checkpoint"], a["epoch"], a["run_name"] or "—", _f(al, 4), _f(1 - al, 4)))
    A("")
    A("`CLAUDE.md` records \"alpha drifted 0.49->0.39 in 3 epochs\". That line comes from")
    A("the 3-epoch placeholder checkpoint, which no longer exists on disk (it was")
    A("overwritten, per the audit's 5.5). On the checkpoints that do exist the value")
    A("has moved further toward the learned graph. A dated correction has been added to")
    A("`CLAUDE.md` rather than editing the original line.")
    A("")

    # ---------------------------------------------------------------- limits
    A("## Limitations")
    A("")
    A("**This is the model's parameter, not its behaviour.** `A_sem` is one of two")
    A("supports and enters only through the `(1 - alpha)` term of the first one. A")
    A("weight in `A_sem` is not the same thing as influence on a prediction: the")
    A("adaptive support, the temporal stack, and the readout all intervene. The")
    A("explainer analysis is what speaks to behaviour; this speaks to structure.")
    A("")
    A("**\"Off-adjacency\" still means \">{} m by road\".** The adjacency is a".format(
        _f(g["cutoff_m"], 0)))
    A("thresholded Gaussian kernel on directed road distance (sigma = {} m,".format(
        _f(g["sigma_m"], 1)))
    A("kappa = 0.1), which reduces exactly to that cutoff, and most non-adjacent pairs")
    A("have no road distance recorded at all.")
    A("")
    A("**Three checkpoints, not a trajectory.** Two are from the traffic-only run at")
    A("different epochs and one is a separate fusion run. This is not a per-epoch")
    A("record — the per-epoch alpha CSV for the real training run lives Colab-side")
    A("(audit 8.3) and is not on disk. Cross-checkpoint agreement here mixes epoch")
    A("drift with run-to-run variation and cannot separate them.")
    A("")
    A("**Row-normalised per source.** Each source's outgoing weights sum to 1, so a")
    A("target's incoming mass is unnormalised and targets are not directly comparable")
    A("on raw incoming weight. The top-k rule is rank-based and unaffected; the")
    A("cumulative-mass rule is computed per target on unnormalised rows and should be")
    A("read with that in mind.")
    A("")
    A("**Exploratory.** No prespecified analysis plan, thresholds carried over from the")
    A("explainer analysis for comparability. Nothing here is confirmatory.")
    A("")
    return "\n".join(L) + "\n"
